# This is playbook for an application.
# This can invoke any of the avi roles like application, profile or cloud
#
---
- hosts: localhost
  connection: local
  collections:
    - vmware.alb
  tasks:
    - name: Avi Application | Setup App1
      include_role:
        name: aviconfig
      vars:
        avi_config_file: "avi_config.yml"
        avi_creds_file: "vars/creds.yml"
