---
- hosts: localhost
  connection: local
  vars:
    controller: 10.10.25.42
    username: admin
  collections:
    - vmware.alb
  tasks:
    - name: Print Hello
      debug: msg="Hello"

    - name: Print Controller
      debug: msg="{{username}}@{{ controller }}"