# This is example of using vault for storing controller credentials"
---
- hosts: localhost
  connection: local
  vars_files:
    - "vars/creds.yml"
  vars:
    tenant: admin
    avi_controller: localhost
  collections:
    - vmware.alb
  tasks:
    - name: Print Hello
      debug: msg="Hello"

    - name: Print Controller
      debug: msg="{{avi_username}}@{{ avi_controller }} tenant {{tenant}}"
